services:
  - type: web
    name: edtech-backend-nodejs
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    rootDir: ./backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
